function fval = minestimation_test(objective_function, global_param, T_MAX, DRAW_B, DRAW_F, husband_prev_kids, husband_prev_emp,wife_prev_kids, wife_prev_emp,...
 health_w, health_h, emp_mrate_child_wage, emp_mrate_child_wage_m, emp_mrate_child_wage_um, ... 
    emp_m_with, emp_m_without, emp_um_with, emp_um_without, emp_wage_by_educ,emp_wage_by_educ_m, emp_wage_by_educ_um,...
    educ_comp, educ_comp_m,assortative, epsilon_b, epsilon_f,w_draws, h_draws, w_draws_per, tax_brackets, deductions_exemptions, nlsy_trans)

disp('now running (test) parameters...');
fval = objective_function(global_param, 'all', 'text', global_param, T_MAX, DRAW_B, DRAW_F, ...
    husband_prev_kids, husband_prev_emp,wife_prev_kids, wife_prev_emp, health_w, health_h, ...
    emp_mrate_child_wage, emp_mrate_child_wage_m, emp_mrate_child_wage_um, ... 
    emp_m_with, emp_m_without, emp_um_with, emp_um_without, emp_wage_by_educ,emp_wage_by_educ_m, emp_wage_by_educ_um,...
    educ_comp, educ_comp_m,assortative, epsilon_b, epsilon_f,w_draws, h_draws, w_draws_per, tax_brackets, deductions_exemptions, nlsy_trans);
